# Define stages
stages:
  - install
  - test
  - build
  - analyse

# Caching node_modules between jobs
cache:
  paths:
    - node_modules

# Install
install:
  stage: install
  image: node:16
  script:
    - echo "Install the app ..."
    - yarn install
    - echo "Install successfull !"
  only:
    - merge_requests
    - develop
    - master

# Test front Jest
#test-front-jest:
#  stage: test
#  image: node:16
#  script:
#    - echo "ls -la :"
#    - ls -la
#    - echo "Testing the app ..."
#    - yarn run test
#    - echo "Test successfully!"
#  only:
#    - merge_requests
#    - develop
#    - master
  # Makes tests visible from gitlab pipelines !
  #artifacts:
  #  when: always
  #  expire_in: 1 hour
  #  reports:
  #    junit:
  #      - junit.xml
  #  # Save reports for sonar analysis
  #  paths:
  #    - test-report.xml
  #    - coverage/lcov.info

build:
  stage: build
  image: node:16
  script:
    - echo "Building the app ..."
    - yarn run build
    - echo "Build successfull !"
    - echo "Creating artifact of build/"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - merge_requests
    - develop
    - master

# Sonar analysis
sonarqube-check:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: false
  only:
    - merge_requests
    - develop
    - master

