import React from 'react';
import HelpIcon from '../../../../../../components/HelpIcon';

const CondObservedParameter = ({ condObserved, setCondObserved }) => (
  <div className="mt-4">
    <label>
      Conditions Observed
      <HelpIcon
        style={{
          position: 'absolute',
        }}
        content={
          <>
            P-values of the tests of presence of expression of a gene are all
            propagated along the graph of conditions, then corrected for
            multiple testing for each gene and condition. You can choose here to
            see expression for all conditions, or only in conditions actually
            annotated in raw data, excluding conditions generated by propagation
            only.
          </>
        }
      />
    </label>
    <div className="is-flex is-flex-wrap-wrap gene-expr-fields-wrapper mt-2">
      <label className="checkbox ml-2 is-size-7 is-flex is-align-items-center">
        <input
          type="radio"
          checked={condObserved === false}
          onChange={() => setCondObserved(false)}
        />
        <b className="mx-1">All observed and propagated conditions</b>
      </label>
      <label className="checkbox ml-2 is-size-7 is-flex is-align-items-center">
        <input
          type="radio"
          checked={condObserved === true}
          onChange={() => setCondObserved(true)}
        />
        <b className="mx-1">Restrict to conditions observed in annotations</b>
      </label>
    </div>
  </div>
);

export default CondObservedParameter;
